# Generated by Skyramp v1.3.23 on 2026-05-06 18:45:54.872225258 +0000 UTC m=+373.767150305
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output check_permission_deny_hint_integration_test.py \
# 		--output-dir /home/runner/work/spicedb/spicedb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/spicedb/spicedb/tests/scenario_check_permission_deny_hint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8443")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    write_POST_request_body = r'''{
        "schema": "definition user {}\n\ndefinition document {\n  relation viewer: user\n  permission view = viewer\n}"
    }'''
    
    # Execute Request
    write_POST_response = client.send_request(
        url=URL_localhost,
        path="/v1/schema/write",
        method="POST",
        body=write_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert write_POST_response.status_code == 200
    assert skyramp.get_response_value(write_POST_response, "writtenAt.token") is not None

    # Request Body
    check_POST_request_body = r'''{
        "consistency": {
            "minimizeLatency": true
        },
        "permission": "view",
        "resource": {
            "objectId": "doc-deny-hint-test",
            "objectType": "document"
        },
        "subject": {
            "object": {
                "objectId": "user-no-access-hint",
                "objectType": "user"
            }
        }
    }'''
    
    # Execute Request
    check_POST_response = client.send_request(
        url=URL_localhost,
        path="/v1/permissions/check",
        method="POST",
        body=check_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert check_POST_response.status_code == 200
    assert skyramp.get_response_value(check_POST_response, "permissionship") == "PERMISSIONSHIP_NO_PERMISSION"
    assert skyramp.get_response_value(check_POST_response, "debugTrace.check.resource.objectType") == "document"
    assert skyramp.get_response_value(check_POST_response, "debugTrace.check.resource.objectId") == "doc-deny-hint-test"
    assert skyramp.get_response_value(check_POST_response, "debugTrace.check.permission") == "view"
    assert skyramp.get_response_value(check_POST_response, "debugTrace.check.subject.object.objectType") == "user"
    assert skyramp.get_response_value(check_POST_response, "debugTrace.check.subject.object.objectId") == "user-no-access-hint"
    assert skyramp.get_response_value(check_POST_response, "debugTrace.check.result") == "PERMISSIONSHIP_NO_PERMISSION"
    assert "deny:" in skyramp.get_response_value(check_POST_response, "debugTrace.check.source")
    assert "user:user-no-access-hint" in skyramp.get_response_value(check_POST_response, "debugTrace.check.source")
    assert "document:doc-deny-hint-test" in skyramp.get_response_value(check_POST_response, "debugTrace.check.source")
    assert "view" in skyramp.get_response_value(check_POST_response, "debugTrace.check.source")
    assert not skyramp.get_response_value(check_POST_response, "debugTrace.schemaUsed")


if __name__ == "__main__":
    test_integration()
