# Generated by Skyramp v1.3.23 on 2026-05-06 16:25:37.279990811 +0000 UTC m=+285.430459672
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output relation_description_overwrite_clear_integration_test.py \
# 		--output-dir /home/runner/work/spicedb/spicedb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/spicedb/spicedb/tests/scenario_relation-description-overwrite-clear.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8443")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    write_POST_request_body = r'''{
        "schema": "definition user {}\n\ndefinition document {\n\trelation viewer: user description \"Original description\"\n}"
    }'''
    
    # Execute Request
    write_POST_response = client.send_request(
        url=URL_localhost,
        path="/v1/schema/write",
        method="POST",
        body=write_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert write_POST_response.status_code == 200
    assert skyramp.get_response_value(write_POST_response, "writtenAt") is not None

    # Request Body
    write_POST_1_request_body = r'''{
        "schema": "definition user {}\n\ndefinition document {\n\trelation viewer: user\n}"
    }'''
    
    # Execute Request
    write_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/v1/schema/write",
        method="POST",
        body=write_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert write_POST_1_response.status_code == 200
    assert skyramp.get_response_value(write_POST_1_response, "writtenAt") is not None

    # Request Body
    read_POST_request_body = r'''{}'''
    
    # Execute Request
    read_POST_response = client.send_request(
        url=URL_localhost,
        path="/v1/schema/read",
        method="POST",
        body=read_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert read_POST_response.status_code == 200
    assert skyramp.get_response_value(read_POST_response, "schemaText") is not None
    assert 'description' not in skyramp.get_response_value(read_POST_response, "schemaText")
    assert 'relation viewer: user' in skyramp.get_response_value(read_POST_response, "schemaText")


if __name__ == "__main__":
    test_integration()
