# Generated by Skyramp v1.3.23 on 2026-05-06 16:57:10.380233878 +0000 UTC m=+310.790486609
# Command: skyramp generate contract rest http://localhost:8443/v1/schema/write \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output schema_write_backward_compat_contract_test.py \
# 		--output-dir /home/runner/work/spicedb/spicedb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"schema":"definition example/user {}"} \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8443")

# contract test for /v1/schema/write POST
def test_write_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    write_POST_request_body = r'''{
        "schema": "definition example/user {}"
    }'''

    # Execute Request
    write_POST_response = client.send_request(
        url=URL,
        path="/v1/schema/write",
        method="POST",
        body=write_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert write_POST_response.status_code == 200
    assert skyramp.get_response_value(write_POST_response, "writtenAt") is not None
    assert skyramp.get_response_value(write_POST_response, "writtenAt.token") is not None


if __name__ == "__main__":
    test_write_post()
