# Generated by Skyramp v1.3.23 on 2026-05-07 02:58:59.268827181 +0000 UTC m=+661.502709282
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output write_relationships_duplicate_failed_index_integration_test.py \
# 		--output-dir /home/runner/work/spicedb/spicedb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/spicedb/spicedb/tests/scenario_write_relationships_duplicate_failed_index.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8443")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    schema_write_POST_request_body = r'''{
        "schema": "definition user {}\n\ndefinition document {\n  relation writer: user\n}"
    }'''
    
    # Execute Request
    schema_write_POST_response = client.send_request(
        url=URL_localhost,
        path="/v1/schema/write",
        method="POST",
        body=schema_write_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert schema_write_POST_response.status_code == 200
    assert skyramp.get_response_value(schema_write_POST_response, "writtenAt.token") is not None

    # Request Body
    write_POST_request_body = r'''{
        "updates": [
            {
                "operation": "OPERATION_CREATE",
                "relationship": {
                    "relation": "writer",
                    "resource": {
                        "objectId": "dupdoc",
                        "objectType": "document"
                    },
                    "subject": {
                        "object": {
                            "objectId": "dupuser",
                            "objectType": "user"
                        }
                    }
                }
            },
            {
                "operation": "OPERATION_CREATE",
                "relationship": {
                    "relation": "writer",
                    "resource": {
                        "objectId": "dupdoc",
                        "objectType": "document"
                    },
                    "subject": {
                        "object": {
                            "objectId": "dupuser",
                            "objectType": "user"
                        }
                    }
                }
            }
        ]
    }'''
    
    # Execute Request
    write_POST_response = client.send_request(
        url=URL_localhost,
        path="/v1/relationships/write",
        method="POST",
        body=write_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert write_POST_response.status_code == 400
    assert skyramp.get_response_value(write_POST_response, "code") == 3
    assert "atomic batch failed at index 1" in str(skyramp.get_response_value(write_POST_response, "message"))
    assert skyramp.get_response_value(write_POST_response, "details.0.reason") == "ERROR_REASON_UPDATES_ON_SAME_RELATIONSHIP"
    assert skyramp.get_response_value(write_POST_response, "details.0.metadata.failed_index") == "1"
    assert skyramp.get_response_value(write_POST_response, "details.0.metadata.operations_committed") == "0"
    assert skyramp.get_response_value(write_POST_response, "details.0.metadata.atomic_batch_guarantee") == "all_or_nothing"
    assert skyramp.get_response_value(write_POST_response, "details.1") is None


if __name__ == "__main__":
    test_integration()
